/**
 * GRAND ORDERS — rare, giant holiday orders (separate from the daily board and
 * the rush pop-ups). A worldwide event lands roughly every couple of weeks; the
 * player is warned a few days early ("Valentine's is coming — stores placed a
 * huge order!"), works toward one giant multi-toy order pinned in the Orders
 * tab, and gets a big payday only if it's fully delivered by the holiday. Miss
 * it and you get nothing.
 *
 * Days are day-of-run (1..365, Christmas = 365). Spacing is ~14 days so there's
 * always one within 10–15 days. Add/rename freely — the system reads this list.
 * Quantities and reward are generated by OrdersSystem from the constants below,
 * scaled by how many toys you've unlocked, so the order grows with the player.
 */

export type GrandOrderDef = {
  id: string;
  name: string;
  icon: string;
  /** Deadline day-of-run — must be fully delivered by the END of this day. */
  day: number;
  /** One-line flavor shown in the pinned banner. */
  flavor: string;
  /** Optional toy the holiday emphasizes (asked for in larger quantity). */
  featuredToy?: string;
};

/** Warn the player (and open the order) this many days before the deadline. */
export const GRAND_ANNOUNCE_DAYS_BEFORE = 6;
/** Giant reward: total toy value times this. */
export const GRAND_PAY_MULT = 4;
/** Per-toy-line quantity range (before the featured boost). Deliberately huge. */
export const GRAND_MIN_QTY = 250;
export const GRAND_MAX_QTY = 550;
/** The featured toy is asked for this much more. */
export const GRAND_FEATURED_MULT = 1.6;

export const grandOrderDefs: GrandOrderDef[] = [
  { id: "new_year", name: "New Year's Gala", icon: "🎆", day: 8, flavor: "The world rings in the new year — every store wants a launch-day haul." },
  { id: "winter_expo", name: "Winter Toy Expo", icon: "🏔️", day: 22, flavor: "Buyers pack the Winter Expo and need their catalogs filled." },
  { id: "sled_champs", name: "Sledding Championship", icon: "🛷", day: 36, flavor: "The big race draws crowds — vendors want crates of toys trackside." },
  { id: "valentines", name: "Valentine's Day", icon: "💝", day: 50, featuredToy: "plushy", flavor: "Sweethearts everywhere want something soft and cuddly." },
  { id: "mardi_gras", name: "Mardi Gras Parade", icon: "🎭", day: 64, flavor: "Parade floats need mountains of toys to toss to the crowd." },
  { id: "pi_day", name: "Pi Day Puzzle Fest", icon: "🥧", day: 78, featuredToy: "rubik", flavor: "Puzzle shops celebrate Pi Day with a cube stampede." },
  { id: "spring", name: "Spring Awakening", icon: "🌷", day: 92, flavor: "Spring markets bloom and orders sprout everywhere." },
  { id: "april_fools", name: "April Fools' Bonanza", icon: "🃏", day: 106, flavor: "Prank shops stock up — and this order is no joke." },
  { id: "earth_day", name: "Earth Day Drive", icon: "🌍", day: 120, featuredToy: "train", flavor: "Eco-fairs want wholesome wooden toys by the truckload." },
  { id: "may_day", name: "May Day Market", icon: "🎏", day: 134, flavor: "May Day stalls stretch for miles and every one needs stock." },
  { id: "mothers_day", name: "Mother's Day", icon: "💐", day: 148, featuredToy: "plushy", flavor: "Every child wants the perfect gift for mom." },
  { id: "founders", name: "Founders' Festival", icon: "🏰", day: 162, flavor: "The town's founding day — a parade of orders down Main Street." },
  { id: "midsummer", name: "Midsummer Fair", icon: "☀️", day: 176, flavor: "The longest day, the biggest fair — demand that never sets." },
  { id: "independence", name: "Independence Blast", icon: "🎆", day: 190, flavor: "Summer festivals want toys to hand out by the crateload." },
  { id: "toy_con", name: "Galactic Toy Con", icon: "🚀", day: 204, featuredToy: "robot", flavor: "The sci-fi mega-con — tin robots are flying off the shelves." },
  { id: "harvest", name: "Harvest Kickoff", icon: "🌻", day: 218, flavor: "The first harvest fairs open and want their stalls stocked." },
  { id: "back_to_school", name: "Back-to-School Rush", icon: "🎒", day: 232, flavor: "Every classroom wants a starter set before the bell rings." },
  { id: "labor_day", name: "Labor Day Haul", icon: "🛠️", day: 246, flavor: "One last summer blowout across every store in town." },
  { id: "autumn", name: "Autumn Equinox Fair", icon: "🍂", day: 260, flavor: "Harvest fairs want toys to celebrate the turning season." },
  { id: "oktoberfest", name: "Oktoberfest Order", icon: "🍺", day: 274, flavor: "The beer halls become toy halls — steins of orders pour in." },
  { id: "halloween", name: "Halloween Spooktacular", icon: "🎃", day: 288, flavor: "Costume shops and trick-or-treat stands need heaps of goodies." },
  { id: "dia_munecos", name: "Día de los Muñecos", icon: "💀", day: 302, flavor: "A festival of little figures — colorful toys in enormous demand." },
  { id: "thanksgiving", name: "Thanksgiving Feast", icon: "🦃", day: 316, flavor: "Families gather and everyone wants gifts on the table." },
  { id: "black_friday", name: "Black Friday Blowout", icon: "🛍️", day: 330, flavor: "The biggest shopping day of the year — stores beg for stock." },
  { id: "solstice", name: "Winter Solstice Wonders", icon: "❄️", day: 344, featuredToy: "train", flavor: "The longest night calls for the brightest toys." },
  { id: "xmas_eve", name: "Christmas Eve Marathon", icon: "🎅", day: 358, flavor: "The final sleigh-load before the big day — give it everything." },
];
